---
- name: 'install_vmware_horizon : install patchelf'
  package:
    name:
    - patchelf
- become_user: '{{ development_echo.dev_users[0] }}'
  git:
    depth: 1
    dest: /tmp/vmware-keymaps
    repo: 'https://aur.archlinux.org/vmware-keymaps.git'
    version: '{{ development_echo.install_vmware_horizon.vmware_keymaps.commit_hash }}'
  name: 'install_vmware_horizon : vmware-keymaps : clone package'
- become_user: '{{ development_echo.dev_users[0] }}'
  name: 'install_vmware_horizon : vmware-keymaps : build'
  shell:
    chdir: /tmp/vmware-keymaps
    cmd: makepkg
- name: 'install_vmware_horizon : vmware-keymaps : install'
  shell:
    chdir: /tmp/vmware-keymaps
    cmd: >-
      pacman --noconfirm --upgrade
      vmware-keymaps-{{ development_echo.install_vmware_horizon.vmware_keymaps.version }}-any.pkg.tar.zst
- become_user: '{{ development_echo.dev_users[0] }}'
  git:
    depth: 1
    dest: /tmp/vmware-horizon-client
    repo: 'https://aur.archlinux.org/vmware-horizon-client.git'
    version: '{{ development_echo.install_vmware_horizon.vmware_horizon_client.commit_hash }}'
  name: 'install_vmware_horizon : vmware-horizon-client : clone package'
- become_user: '{{ development_echo.dev_users[0] }}'
  name: 'install_vmware_horizon : vmware-horizon-client : build'
  shell:
    chdir: /tmp/vmware-horizon-client
    cmd: makepkg
- name: 'install_vmware_horizon : vmware-horizon-client : install'
  shell:
    chdir: /tmp/vmware-horizon-client
    cmd: >-
      pacman --noconfirm --upgrade
      vmware-horizon-client-{{ development_echo.install_vmware_horizon.vmware_horizon_client.version }}-x86_64.pkg.tar.zst
      vmware-horizon-integrated-printing-{{ development_echo.install_vmware_horizon.vmware_horizon_client.version }}-x86_64.pkg.tar.zst
      vmware-horizon-mmr-{{ development_echo.install_vmware_horizon.vmware_horizon_client.version }}-x86_64.pkg.tar.zst
      vmware-horizon-rtav-{{ development_echo.install_vmware_horizon.vmware_horizon_client.version }}-x86_64.pkg.tar.zst
      vmware-horizon-smartcard-{{ development_echo.install_vmware_horizon.vmware_horizon_client.version }}-x86_64.pkg.tar.zst
      vmware-horizon-tsdr-{{ development_echo.install_vmware_horizon.vmware_horizon_client.version }}-x86_64.pkg.tar.zst
      vmware-horizon-usb-{{ development_echo.install_vmware_horizon.vmware_horizon_client.version }}-x86_64.pkg.tar.zst
