---
- name: 'install_fluxbox : Install packages'
  package:
    name:
    - alsa-utils # Audio drivers and controls
    - feh # Image viewer, needed for setting the background
    - fluxbox # Window manager
    - imagemagick # Image command line tool/screenshots
    - ttf-ubuntu-font-family # Fonts, needed for fluxbox to start successfully
    - xclip # clipboard
    - xcompmgr # Transparency
    - xorg-apps # A bunch of X utilities
    - xorg-server # The X server, makes the world go round
    - xorg-xclock # Clock
    - xorg-xinit # xinit, starts X server
    - xorg-xmessage # X server message display, needed for when things go bad
    - xterm # A terminal

- name: 'install_fluxbox : Copy xinitrc'
  copy:
    dest: /etc/X11/xinit/xinitrc
    mode: '644'
    owner: root
    src: xinitrc
