---
- changed_when: false
  ignore_errors: 'yes'
  k8s:
    kind: Namespace
    kubeconfig: /etc/kubernetes/admin.conf
    name: default
    state: present
  name: 'create_cluster : check if cluster is currently running'
  register: cluster_check
- name: 'create_cluster : Initialize first master'
  shell:
    cmd: >-
      kubeadm init --control-plane-endpoint="{{
      k8s_deploy_group.control_plane_endpoint }}" --pod-network-cidr="{{
      k8s_deploy_role.pod_network_cidr }}"
  when: cluster_check.failed and "primary_master" in group_names
