---
- name: 'create_cluster : Initialize first master'
  shell:
    cmd: >-
      kubeadm init --control-plane-endpoint="{{
      k8s_deploy_group.control_plane_endpoint }}" --pod-network-cidr="{{
      k8s_deploy_role.pod_network_cidr }}"
  when: '"primary_master" in group_names'
