---
- changed_when: false
  ignore_errors: 'yes'
  k8s:
    kind: Namespace
    kubeconfig: /etc/kubernetes/admin.conf
    name: default
    state: present
  name: 'create_cluster : check if cluster is currently running'
  register: cluster_check
- name: 'create_cluster : Initialize first master'
  shell:
    cmd: >-
      kubeadm init --control-plane-endpoint="{{
      k8s_deploy_group.control_plane_endpoint }}" --pod-network-cidr="{{
      k8s_deploy_role.pod_network_cidr }}"
  when: cluster_check.failed and "primary_master" in group_names
- name: 'create_cluster : Remove taint from masters that are also workers'
  ignore_errors: 'yes'
  changed_when: result is succeeded
  register: result
  shell:
    cmd: >-
      kubectl taint node {{ inventory_hostname }}
      node-role.kubernetes.io/master-
  when: '"masters" in group_names and "workers" in group_names'
- k8s:
    definition: '{{ lookup("file", "flannel.yml") }}'
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
  name: 'create_cluster : Apply Flannel network plugin'
