---
- include_tasks: install_packages.yml
- include_tasks: install_container_runtime.yml
- include_tasks: configure_firewall.yml
- include_tasks: install_kube_packages.yml
- include_tasks: prepare_node.yml
